services:
  - type: worker
    name: history-ege-bot
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MINI_APP_URL
        value: https://history-ege.vercel.app
      - key: API_URL
        value: https://history-ege.vercel.app
      - key: ADMIN_API_SECRET
        sync: false