FROM node:20-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install --production

# Копируем исходники
COPY src/ ./src/
COPY bot.js .

# Создаём пользователя для безопасности
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app

USER appuser

# Запуск
EXPOSE 3000
CMD ["node", "bot.js"]